title: Ethan Davis
theme: jekyll-theme-cayman
exclude:
  - README.md
  - Makefile
  - cspell.config.yaml
  - package.json
  - package-lock.json
  - node_modules
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache
  - vendor
